### PR TITLE
make memoize exportable

### PR DESCRIPTION
**Pull request by ellbee**
Addresses #7

### CODE REVIEW

**Comment by faassen** [comment]
I haven't followed along various discussions (I need to catch up but work is so busy lately) so I may be talking nonsense. I vaguely recall thinking at some point: it's a good thing memoize is internal as it's not really a general memoize function. Does that objection make any sense?

**Comment by ellbee** [comment]
Yeah, there are two things about this function which the user might not expect. 

* The cache size is fixed to 1
* We don't serialise/hash the value of the arguments when they are objects (i.e. if you deeply mutate an argument we will always get a cache hit due to reference equality).

Possible solutions:

* Documentation
* Rename exported memoize function
* Make memoize less surprising by implementing a variable cache size and providing the option for value equality for objects, maybe by using a third party memoize function (lodash?). If we did this I guess there is no reason to export the function at all because I think the original problem could be solved by changing the cache and equality settings.

**Comment by ellbee** [comment]
@HeyImAlex, @speedskater Any thoughts on making memoize more configurable instead of exporting it?

**Comment by speedskater** [comment]
@ellbee sorry for the delay but i was a bit busy the last days.

I like your idea making the memoization strategy configurable as a configuration option for creating selectors (there it would be able to use lodash memoization, database based ones or other fancy strategies). 

As far as i understand, in our internal use case the default memoization functions should  be a function which uses cache size 1 and does reference equality checking. The reason is that a common memoization function like the one provided by lodash might store all previous call results, which can result in a significantly increased memory footprint for the whole application.

Maybe for our internal memoization function the name memoize is missleading. So maybe it might be less confusing if we name the function buffer or createCached or something totally different. Than it might be less confusing in the exported case. Or do you know of any library which exports the same kind of memoization/buffer function?
What do you think?

**Comment by banderson** [comment]
re: configuration, the one thing I see as obviously useful would be the cache size. Having it set to 1 was a surprise to me. Keeping the reference equality constraint is a good thing I think, and expected since it's advertised as using with redux which requires immutability.

**Comment by ellbee** [comment]
@banderson Yes, I agree about the cache size being surprising, that is definitely something I would like to be configurable. The downside is that I think allowing a cache size bigger than 1 would mean that straight reference equality is not going to work with objects. Redux's immutability means the object reference (and therefore the key into the cache) is going to be different each time. Even when an objects value is the same as some previous object in the cache it won't produce a cache hit. We'd need to hash or JSON.stringify the object to get a value we could use a cache key.

**Comment by ellbee** [comment]
@speedskater I pretty much agree. I'll have a think about whether there is a better name for memoize.

**Comment by banderson** [comment]
@ellbee I see the issue there. That could still be useful for those providing a custom equality function, however. No urgent need here, just my 2 cents :)

**Comment by ellbee** [comment]
Probably superseded by #32

**Pull request closed without merging**
